In [6]:
import numpy as np

class Data():
#Data.X_train
#Data.y_train
#Data.X_test
#Data.y_train
#Data.train_image_count
#Dara.test_image_count
#Data.image_col
#Data.image_row
#Data.image_dim

    def __init__(self):
        self.X_train = None
        self.y_train = None
        self.X_test = None
        self.y_train = None
        self.train_image_count = None
        self.test_image_count = None
        self.image_col = None
        self.image_row = None
        self.image_dim = None

        self.loadTrainData()
        self.loadTrainLabel()

    def loadTrainData(self):
        with open('./data/train-images-idx3-ubyte', 'rb') as inputfile:
            content = inputfile.read()
        self.train_image_count = int.from_bytes(content[4:8], 'big') # 手書き画像枚数
        self.image_row = int.from_bytes(content[8:12], 'big') # 手書き画像行数
        self.image_col = int.from_bytes(content[12:16], 'big') # 手書き画像列数
        images = np.frombuffer(content, np.uint8, -1, 16)# 手書き画像データの読み込み
        self.X_train = images.reshape(self.train_image_count, self.image_row, self.image_col, 1) # 一つの画像を一列にまとめる

    def loadTrainLabel(self):
        with open('./data/train-labels-idx1-ubyte', 'rb') as inputfile:
            content = inputfile.read()
        labels = np.frombuffer(content, np.uint8, -1, 8) #ラベルの読み込み(5,0,4,...)
        one_hot_label = np.zeros((self.train_image_count, 10))  #one_hot_vectorに変換
        one_hot_label[np.arange(self.train_image_count), labels] = 1
        self.y_train = one_hot_label

In [7]:
data = Data()

In [152]:
input_dim = data.image_row * data.image_col
hidden_dim = 400 #これはパラメータ
output_dim = 10 #出力の次元は0から9まで
np.random.seed(0)
#initialize parameter, weight, bias
x = data.X_train[0].reshape([input_dim, 1])
#input→hidden
w1 = np.random.rand( input_dim * hidden_dim).reshape([hidden_dim ,input_dim]) #0に初期化
b1 = np.zeros([hidden_dim, 1]) #0で初期化
#hidden→output
w2 = np.random.rand(hidden_dim * output_dim).reshape(output_dim, hidden_dim) #0~1の間でランダムに初期化
b2 = np.zeros([output_dim, 1])

In [163]:
#Forward Propagation
h1 = w1.dot(x) + b1 #input→hidden
a1 = np.tanh(h1) #activate function
o1 = w2.dot(a1) + b2 #hidden→output
exp_y1 = np.exp(o1) 
y_probs = exp_y1 / np.sum(exp_y1) #softmax 

In [177]:
Y = data.y_train[0].reshape([10,1])
y = y_probs

In [187]:
#Back propagation
#Loss function for cross entropy and softmax function
L = -1 * np.sum(Y * np.log (y))
#Error for output→hidden
delta_out = y - Y
#Error for hidden→input
delta_hidden = (1-np.power(a1, 2)) * w2.T.dot(delta_out)

In [199]:
#update rate
dw2 = delta_out.dot(a1.T)
db2 = delta_out
dw1 = delta_hidden.dot(x.T)
db1 = delta_hidden

In [201]:
#update parameter
epsilon = 0.3 #データをもとに変化させるのが良い
w2 += epsilon * dw2
b2 += epsilon * db2
w1 += epsilon * dw1
b1 += epsilon * db1

In [209]:
data.X_train.shape[0]
X = data.X_train

In [210]:
input_dim = X.shape[1] * X.shape[2]

In [211]:
input_dim

784

In [215]:
X[1].reshape([input_dim, 1]).shape

(784, 1)

In [222]:
np.zeros((20,10))

array([[ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.

In [224]:
w1 = np.random.rand([hidden_dim, input_dim])

TypeError: 'list' object cannot be interpreted as an integer

In [233]:
Y = data.y_train

In [231]:
Y[0].reshape([output_dim, 1])

array([[ 0.],
       [ 0.],
       [ 0.],
       [ 0.],
       [ 0.],
       [ 1.],
       [ 0.],
       [ 0.],
       [ 0.],
       [ 0.]])

In [232]:
output_dim

10

In [236]:
Y[1]

array([ 1.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.])

In [237]:
data.image_col.a = 1

AttributeError: 'int' object has no attribute 'a'